### ISSUE TITLE
Thread aktualisiert nicht das Hauptobjekt

### ISSUE THREAD

**Issue by tanns2** [shylux/ch.bfh.bti7081.s2015.rot#11]
In der Klasse TestStatePattern wird eine neue TimeActivity erstellt, die dann einen Thread startet. Der Thread hat eine Referenz auf die Activity und setzt nach ablaufen des Soft und Hardlimites den Status der Activity auf Failed -> das funktioniert. Allerdings sind die Änderungen in der Callerklasse TestStatePattern nicht wirksam, obwohl die Activity als volatile deklariert ist und sogar der Thread durch das Interface "Shareable" in der TestStatePatternklasse die Methode setActivty aufruft und wieder die aktuelle Activity (sie ist korrekt, der Status stimmt) der Instanzvariable zuweisen soll. Der Leider cheggt das die TestStatePattern allerdings nicht richtig und es ist immer noch auf dem Initialstatus "TimeActivityReady". </latein>

Kann jemand vielleicht helfen oder sieht den Fehler? Der Ablauf des Statepattern funktioniert sonst, "einzig" das Teilen der Variable macht noch Probleme.

Vielen Dank euch allen

https://github.com/shylux/ch.bfh.bti7081.s2015.rot/blob/StatePattern/src/main/java/ch/bfh/bti7081/s2015/red/PatientApp/lifeUp/InProgress.java
https://github.com/shylux/ch.bfh.bti7081.s2015.rot/blob/StatePattern/src/main/java/ch/bfh/bti7081/s2015/red/PatientApp/lifeUp/TimeActivityManager.java
https://github.com/shylux/ch.bfh.bti7081.s2015.rot/blob/StatePattern/src/main/java/ch/bfh/bti7081/s2015/red/PatientApp/lifeUp/TimeActivityReady.java

**Comment by shylux** [comment]
https://github.com/shylux/ch.bfh.bti7081.s2015.rot/blob/StatePattern/src/main/java/TestStatePattern.java#L28-L37

soft limit in 3 sekunde, hard in 5. Du wartisch 1 sekunde. Erwartetes resultat: Initialstatus..

**Comment by tanns2** [comment]
Fautsch - s sött InPgroess si -> nid im Ready.

**Comment by tanns2** [comment]
Fautsch - s sött InPgroess si -> nid im Ready.

**Comment by shylux** [comment]
Cha si das das nüt mit threads ds tüe het. Mach mal vorem sleep es print.
Du hesch öppe 4 setActivity methode und die klasse übergebe alli no sich selber. I vermuete dr bock ir logik.

Ah und btw. Du machsch threads wo über stunde oder tage chöi sleepe. je nach activity. I chader nid sege wo oder wenn, aber das wird faile.
Gschider weri 1 thread wo e liste vo date het wos immer weider geit ga prüefe. Eventuell gits das scho vo vaadin. Oder de nimsch e java library.

**Comment by tanns2** [comment]
Aso de meinsch dassi e Thread ha wo e art e HashMap oder e ActivityID het mit de dazueghörige Soft u HardTimes wos so einisch ir stung geit ga chegge u ggf. dr Status setzt? De wär mr ja widr bim gliche Problem, wüu dr Thread när nid cha z Houptobjekt ga ändere odr gsehni das fautsch?

**Comment by shylux** [comment]
Ready sötti ja am afang gsetzt werde. Lueg its mal öb das vorem sleep korrekt isch.

**Comment by tanns2** [comment]
S isch korrekt: Wüu im SetActivty wirds ja eh widr neu gsetzt. Aber i dues schüsch aues ändere dass i ei Thread ha, isch mr o rächt, de ischs ni so inenang verflochte. Merci

**Comment by shylux** [comment]
En art singleton background worker wode diner events mit callbacks chasch registriere sötti passe.
@tscheims1 Was meinsch du derzue?

**Comment by tanns2** [comment]
wo wei mr de dä instanziere? muess ja generou verfüegbar si? u Serialisierbar muess er sicher o si, schüsch machts irgendwie nid so sinn

**Comment by shylux** [comment]
singleton^^
und wieso wosch de serialisiere? wosch dr worker id datebank spichere? :stuck_out_tongue_closed_eyes:

**Comment by tanns2** [comment]
WO wei mr de dä instanziere - isch ja eher generou. nei i has o grad gmerkt, de cha ja d activites ga reiche ir DB.

**Comment by shylux** [comment]
Lueg zersch mal a was e singleton isch :wink:

**Comment by tanns2** [comment]
i weisswas singelton isch
nume einisch es objekt instanzierbar mache.

**Comment by shylux** [comment]
De verstani dini frag wege WO nid...
Du machsch überall wode klass bruchsch es `XX.getInstance()`.

**Comment by tanns2** [comment]
okok.
U i füehre eifach e ArrayList<Activity> woni när au stung odr so due düreloope u prüefe, ob z limit abgloffe isch. I probieres bis am Friti z Implementiere.

**Comment by tscheims1** [comment]
@shylux 
zwar chli spät: abr i ha em tanner geschtr öppis ähnlech vorgschlage -> ha a dere idee nüt uszsetzä
