### ISSUE TITLE
Circular Reference Problem: Serialization

### ISSUE THREAD

**Issue by tanns2** [shylux/ch.bfh.bti7081.s2015.rot#19]
Momentan versucht die GSON-Libary noch rekursiv die Objekte zu serialisieren. Da aber beim StatePattern eine 1:1 Beziehung ist, endet dies mit einem StackOverflow. Gemàss Dozent kann mit einem JSON-Ignore oder dergleichen dieses Problem behoben werden. Bitte um Hilfe. 
Gruss & Danke @tscheims1

**Comment by tscheims1** [comment]
Jedes Element, welches serialisiert werden soll, muss den Präfix @Expose tragen

**Comment by shylux** [comment]
Was sehr viele sind. Zudem muss eine andere Funktion zum serialisieren in gson aufgerufen werden: `GsonBuilder.excludeFieldsWithoutExposeAnnotation()`
Recht dämlich.

**Comment by shylux** [comment]
```
Note that another way to achieve the same effect would have been to just mark the password field as transient, and Gson would have excluded it even with default settings. The @Expose annotation is useful in a style of programming where you want to explicitly specify all fields that should get considered for serialization or deserialization.
```

Das habe ich auch probiert. Scheint aber nicht zu funktionieren..

**Comment by tscheims1** [comment]
ihr müsst auf dem pull request schauen und nicht auf dem master...
(siehe oben)
https://github.com/shylux/ch.bfh.bti7081.s2015.rot/commit/b947c581dee5757d62a163f92863fe314c040e89
